core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path(
        'result/<int:year>/<str:result>/',
        views.ResultView.as_view(),
        name='result'
    ),
]

leap_year/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('core.urls', 'core'), namespace='core')),
]

if settings.DEBUG:
    # Fazer Django servir static e media quando em DEBUG = True
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from .utils import leap_year


class LeapYearForm(forms.Form):
    year = forms.CharField(label='Ano')

    def clean_year(self):
        year = self.cleaned_data['year']
        try:
            year = int(year)
        except ValueError:
            raise forms.ValidationError('Informe um ano válido')
        return year

    def is_leapyear(self):
        return leap_year(int(self.cleaned_data['year']))

core/views.py
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect, Http404
from .forms import LeapYearForm


class ResultView(TemplateView):
    template_name = 'core/result.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        result = kwargs.get('result')
        year = kwargs.get('year')
        if result == 'bissexto':
            ctx['msg'] = 'O ano {0} é bissexto.'.format(year)
            ctx['status'] = 'success'
        elif result == 'nao-bissexto':
            ctx['msg'] = 'O ano {0} não é bissexto.'.format(year)
            ctx['status'] = 'danger'
        else:
            raise Http404
        return ctx


class IndexView(FormView):
    template_name = 'core/index.html'
    form_class = LeapYearForm
    success_url = '/result/{0}/{1}/'

    def form_valid(self, form):
        url = self.success_url.format(
            form.cleaned_data['year'],
            'nao-bissexto'
        )
        if form.is_leapyear():
            url = self.success_url.format(
                form.cleaned_data['year'],
                'bissexto'
            )
            return HttpResponseRedirect(url)
        return HttpResponseRedirect(url)

core/templates/core/base.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Levi Macario">
        <title>Anos Bissextos</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/docs/dist/bootstrap.min.css' %}" rel="stylesheet">

        <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                -ms-user-select: none;
                user-select: none;
            }

            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                font-size: 3.5rem;
                }
            }
        </style>
        <!-- Custom styles for this template -->
        <link href="{% static 'css/floating-labels.css' %}" rel="stylesheet">
        <link href="{% static 'css/custom.min.css' %}" rel="stylesheet">
    </head>
    <body>

    <form class="form-signin" action="." method="POST">
        {% block content %}{% endblock %}
        
        <p class="mt-5 mb-3 text-muted text-center">© Levi Macario</p>
    </form>


</body></html>

core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    {% csrf_token %}
    <div class="text-center mb-4">
        <img class="mb-4" src="{% static 'img/29_de_fevereiro.jpg' %}" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Anos bissextos</h1>
        <p>
            Olá! Tudo bem? ;) <br>
            Informe abaixo o ano que deseja descobrir se é um ano bissexto.
        </p>
    </div>

    <div class="form-label-group {% if form.year.errors %}has-error{% endif %}">
        <input type="text" id="inputEmail" name="year" class="form-control" placeholder="Ano">
        <label for="inputEmail">Ano</label>
        {% if form.year.errors %}
            {{ form.year.errors }}
        {% endif %}
    </div>

    <button class="btn btn-lg btn-primary btn-block" type="submit">Verificar</button>
{% endblock %}

core/templates/core/result.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
    {% csrf_token %}
    <div class="text-center mb-4">
        <img class="mb-4" src="{% static 'img/29_de_fevereiro.jpg' %}" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Anos bissextos</h1>
        <p>
            Olá! Tudo bem? ;) <br>
        </p>
    </div>

    <div class="alert alert-{{ status }}">
        <b>{{ msg }}</b>
    </div>

    <a class="btn btn-lg btn-primary btn-block" href="{% url 'core:index' %}">Nova pesquisa</a>
{% endblock %}